project:
  type: website

website:
  title: "BIOC13 Statistics"
  description: "Materials for the Statistics section of BIOC13, VT25"

  open-graph: true

  page-footer: 
    left: "Materials under a [CC-BY-SA-4.0 License](https://creativecommons.org/licenses/by-sa/4.0/deed.en)"
    right:  "Built by [Iain R. Moodie](https://irmoodie.com) with [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    collapse: true
    align: center
    style: floating
    search: true
    collapse-level: 0
    contents:
      - section: "Introduction to R"
        contents:
          - href: exercises/02_intro_to_r.qmd
            text: "Getting familiar with R"
          - href: exercises/01_local_r.qmd
            text: "Installation guide"
      - section: "Introduction to inference (Day 1)"
        contents:
          - href: slides/intro_to_inference.qmd
            text: "Slides"
          - href: exercises/03_inference.qmd
            text: "Exercises"
          - href: exercises/03_inference_extra.qmd
            text: "Exercises (extra)"
      - section: "Computational statistics (Day 2)"
        contents:
          - href: slides/computational_statistics.qmd
            text: "Slides"
          - href: exercises/04_statistics.qmd
            text: "Exercises"
          - href: exercises/04_statistics_extra.qmd
            text: "Exercises (extra)"
      - section: "Help beyond the exercises"
        contents:
          - href: help.qmd
            text: Useful resources

format:
  html:
    theme: [cosmo, brand, styles.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\\/\\/irmoodie\\.com\\/custom
execute:
  freeze: auto

# "#61599d" "#c36377" "#f2af4a"