---
title: "Additional resources"
---

In this section of the course, we have been using an R package called `infer` to perform randomisation and resampling based statisitcs. Since we have only had two days, we have not had a chance to go through examples of every sort of analysis you might want to do. However, the framework you have been using for calculating confidence intervals and hypothesis testing can be applied extrememly broadly, and you can likely use them to answer any ecological question you come up with on this course.

Below I have linked you to some materials which should help with that.

---

### Help with implementing your statistical methods

 - The [getting to know `infer` vignette](https://infer.tidymodels.org/articles/infer.html)
  - This contains a walk through of some examples using `infer` with commentary, explaining things in detail.
- The [full `infer` pipeline examples vignette](https://infer.tidymodels.org/articles/observed_stat_examples.html)
  - This contains examples of almost every possible analysis with `infer`, but with limited commentary. If you know what you want to do, but can't quite make it work, check this page.
- There are also [other articles on the `infer` website](https://infer.tidymodels.org/articles/) that contain helpful examples.

### Help with understanding the statistical methods

- The [Statistical Inference with infer section of ModernDive (Ch. 7-10)](https://moderndive.com/v2/index.html) is a  beginner friendly text that follows the style of statistical analysis we have been doing in this part of the course.

### Help with general working with data in R

- For help with importing, data handling and basic plotting, the [Data Science with tidyverse section of ModernDive](https://moderndive.com/v2/index.html) is a beginner friendly text that will have examples for most things you will want to do.
  - If something is not covered, check out [R for Data Science](https://r4ds.hadley.nz/).

### Advice for using AI tools to generate code

AI tools (ChatGPT, Gemini, Deepseek, etc) are going to be both extremely helpful and extremely confusing if you prompt them to provide code. For the output to be more helpful considering what we have covered in this section, at the end of your question, paste the following text:

> Use the tidyverse package and style of coding. Use the base R pipe. Use the infer package for all statistics, and use resampling and/or randomisation approaches.

For example, if I prompt ChatGPT with:

> How do I do an anova in R?

I get this: [https://chatgpt.com/share/68da6440-b3e4-8009-875a-c268999f45be](https://chatgpt.com/share/68da6440-b3e4-8009-875a-c268999f45be)

But if I add the prompt text above and instead use:

> How do I do an anova in R? Use the tidyverse package and style of coding. Use the base R pipe. Use the infer package for all statistics, and use resampling and/or randomisation approaches.

I get this: [https://chatgpt.com/share/68da6458-4184-8009-8889-448b68f72ed5](https://chatgpt.com/share/68da6458-4184-8009-8889-448b68f72ed5)

The second answer is much more helpful for this course.

For general statistics help, include the terms "randomisation based inference" or "resampling based inference" or "computational statistics". These are the methods we have covered here, as opposed to more mathematical based inference methods.

### Access to BIOB11 materials

BIOB11 materials can be accessed [here](https://irmoodie.com/biob11).




